# 데이터 확인

In [1]:
csv_path = "C:\Potenup\Drug-Detection-Chatbot\data\\drug_json_data.csv"

In [2]:
import pandas as pd
data = pd.read_csv(csv_path)

In [49]:
origin_data = data.copy()

In [37]:
data.columns

Index(['id', 'type', 'file_name', 'width', 'height', 'imgfile', 'drug_N',
       'drug_S', 'back_color', 'drug_dir', 'light_color', 'camera_la',
       'camera_lo', 'size', 'item_seq', 'leng_long', 'leng_short', 'thick',
       'dl_mapping_code', 'dl_idx', 'dl_name', 'dl_name_en', 'dl_material',
       'dl_material_en', 'dl_custom_shape', 'dl_company', 'dl_company_en',
       'di_company_mf', 'di_company_mf_en', 'di_item_permit_date',
       'di_class_no', 'di_etc_otc_code', 'di_edi_code', 'chart', 'drug_shape',
       'print_front', 'print_back', 'color_class1', 'color_class2',
       'line_front', 'line_back', 'img_regist_ts', 'form_code_name',
       'mark_code_front_anal', 'mark_code_back_anal', 'mark_code_front_img',
       'mark_code_back_img', 'mark_code_front', 'mark_code_back',
       'change_date', 'area', 'iscrowd', 'bbox', 'category_id', 'ignore',
       'segmentation', 'image_id', 'supercategory', 'category_name', 'folder',
       'c-code'],
      dtype='object')

In [ ]:
data[data['di_etc_otc_code'] == '일반의약품']['di_class_no'].unique()

array(['[02390]기타의 소화기관용약', '[01310]안과용제', '[01410]항히스타민제',
       '[03980]종합대사성제제', '[01140]해열.진통.소염제', '[06420]구충제', '[02150]혈관보강제',
       '[03130]비타민 B제(비타민 B1을 제외)', '[02330]건위소화제',
       '[03990]따로 분류되지 않는 대사성 의약품', '[03210]칼슘제', '[02380]하제, 완장제',
       '[03160]혼합비타민제(비타민AD 혼합제제를 제외)', '[02220]진해거담제', '[01320]이비과용제',
       '[01240]진경제', '[02190]기타의 순환계용약', '[02340]제산제',
       '[03140]비타민 C 및 P제', '[02310]치과구강용약', '[02290]기타의 호흡기관용약',
       '[03110]비타민 A 및 D제', '[03190]기타의 비타민제', '[02320]소화성궤양용제',
       '[02370]정장제', '[01220]골격근이완제', '[02350]최토제, 진토제', '[03950]효소제제',
       '[03910]간장질환용제', '[01150]각성제,흥분제', '[02550]비뇨생식기관용제(성병예방제포함)',
       '[02630]화농성질환용제', '[04900]기타의 조직세포의 기능용의약품', '[02540]피임제', nan,
       '[03920]해독제', '[01190]기타의 중추신경용약', '[02110]강심제',
       '[03150]비타민 E 및 K제', '[01120]최면진정제', '[03250]단백아미노산제제',
       '[02360]이담제', '[03220]무기질제제', '[03120]비타민 B1제', '[02560]치질용제',
       '[01490]기타의 알레르기용약', '[03290]기타의 자양강장변질제', '[02180]동맥경화용제',
       '[02590]기타의 비뇨생식기관 및 항문용약', '[04290]기타의 종양치료제', '[02690]기타의 외피용약',
       '[01900]기타의 신경계및 감각기관용 의약품'], dtype=object)

In [80]:
data[data['di_etc_otc_code'] == '일반의약품' ]['dl_material'].unique()

array(['트리메부틴말레산염', '빌베리건조엑스', '클로르페니라민말레산염|벨라돈나총알칼로이드|페닐레프린염산염',
       '건조레드클로버엑스', '아세트아미노펜|이소프로필안티피린|카페인무수물', '알벤다졸', '클로르족사존|아세트아미노펜',
       '이부프로펜아르기닌', '미세정제플라보노이드분획물',
       '티아민질산염|리보플라빈3배산|니코틴산아미드|판토텐산칼슘|피리독신염산염|폴산|시아노코발라민1000배산|산화아연',
       '디아스타제·프로테아제·셀룰라제|프로자임|디메티콘|판크레아틴|DL-카르니틴염산염', '덱시부프로펜',
       '금은화|연교|두시|우방자|박하|길경|감초|담죽엽|형개|영양각',
       '지황|당귀|목통|황금|택사|차전자|감초|치자|용담|육계|생강|대황|마황|연교', '아세트아미노펜|클로르족사존',
       '탄산칼슘 95%과립|농축콜레칼시페롤 과립', '세티리진염산염', '펙소페나딘염산염',
       '도큐세이트나트륨|센나엽가루|Tinnevelly 센나열매가루|비사코딜', '탄산칼슘|농축콜레칼시페롤과립',
       '아세트아미노펜|푸르설티아민',
       '리보플라빈부티레이트|피리독신염산염|제피아스코르브산|L-시스테인|니코틴산아미드|판토텐산칼슘|비오틴|의이인엑스',
       '반하|황금|건강|인삼|감초|대추|황련|이상 연조엑스로서', '아세트아미노펜|카페인무수물|에텐자미드',
       '벤포티아민|리보플라빈|니코틴산아미드|판토텐산칼슘|피리독신염산염|시아노코발라민1000배산|콜린타르타르산염|이노시톨|비오틴|폴산|산화아연|아스코르브산과립97%',
       '암브록솔염산염', '구풍해독탕건조엑스', '시트르산칼슘수화물|콜레칼시페롤과립|시아노코발라민|폴산',
       '클로닉신리시네이트', '부틸스코폴라민브롬화물|아세트아미노펜', '은행엽건조엑스',
       '라니티딘염산염|산화마그네슘|규산알루민산마그네슘|수산화알루민산마그네슘',
       '이부프로펜|알릴이소프로필아세틸우레아|카페인무수물', '판크레아틴I|우담즙건조엑스|디메티콘|셀룰라제',
       '아세트아미노펜|부틸스코폴라민브롬화물', '탄산마그네슘|스코폴리아엑스10배산|디아스타제·프로테아제100|탄산수소나트륨',
       '아스코르브산97%과립', '아세트아미노펜|에텐자미드', '판크레아틴|헤미셀룰라제|디메치콘|우르소데옥시콜산',
       '아스피린장용과립', '플루르비프로펜', '에키나시아푸르푸레아 허바팅크|에키나시아푸르푸레아 뿌리팅크',
       '콜레칼시페롤농축분말|구연산칼슘',
       '소청룡탕건조엑스|아세트아미노펜|티페피딘히벤즈산염|클로르페니라민말레산염|카페인무수물',
       '클로르족사존|에텐자미드|카페인수화물',
       'dl-메틸에페드린염산염|노스카핀|구아야콜설폰산칼륨|세틸피리디늄염화물수화물|DL-메틸에페드린염산염',
       '이부프로펜|감초|육계|작약|생강', '아세트아미노펜|에페드린염산염|카페인무수물', '콜레칼시페롤농축분말',
       '에페드린염산염|카페인무수물|아세트아미노펜', '알마게이트',
       '아세트아미노펜|에페드린염산염|카페인무수물|아스코르브산97%과립', '아스피린',
       '아세트아미노펜|클로르페니라민말레산염|dl-메틸에페드린염산염|클로페라스틴염산염|카페인무수물|티아민질산염|리보플라빈|아스코르브산',
       '탄산칼슘|농축콜레칼시페롤 과립', '농축콜레칼시페롤과립',
       '아세트아미노펜|덱스트로메토르판브롬화수소산염수화물|dl-메틸에페드린염산염|구아이페네신|클로르페니라민말레산염|카페인무수물',
       nan, '아세트아미노펜', '아세트아미노펜|카페인무수물|에페드린염산염',
       '푸르설티아민염산염|피리독신염산염|시아노코발라민|토코페롤숙시네이트칼슘|판토텐산칼슘 타입S|γ-오리자놀',
       '에페드린염산염|카페인무수물|아세트아미노펜|티아민질산염3배산',
       '건조수산화알루미늄겔|탄산마그네슘|침강탄산칼슘|탄산수소나트륨', '슈도에페드린염산염|트리프롤리딘염산염수화물',
       '리보플라빈부티레이트|피리독신염산염|니코틴산아미드|비오틴|L-시스테인|제피아스코르브산', '나프록센나트륨',
       '마황|작약|건강|감초|계지|세신|오미자|반하', '니자티딘',
       '아세트아미노펜|수도에페드린염산염|클로르페니라민말레산염',
       '아세트아미노펜|클로르페니라민말레산염|수도에페드린염산염|덱스트로메토르판브롬화수소산염수화물|구아야콜설폰산칼륨|아스코르브산|카페인무수물|갈근탕엑스',
       '현초가루|베르베린염화물수화물|아크리놀수화물', '클로르족사존', '로라타딘', '도큐세이트나트륨|센나엽가루|비사코딜',
       '작약감초탕건조엑스|감초|작약',
       '벤포티아민|리보플라빈|니코틴산아미드|판토텐산칼슘|피리독신염산염|시아노코발라민1000배산|콜린타르타르산염|이노시톨|비오틴|폴산|베타카로틴20%과립|농축콜레칼시페롤분말|경질산화마그네슘|무수인산수소칼슘|산화아연',
       '피리독신염산염|d-비오틴|시아노코발라민|토코페롤아세테이트 2배산|폴산|벤포티아민|니코틴산아미드|판토텐산칼슘|산화아연|아스코르브산과립|우르소데옥시콜산|이노시톨|리보플라빈|콜린타르타르산염|셀레늄함유건조효모',
       '시메티콘', '디멘히드리네이트|스코폴라민브롬화수소산염수화물',
       '아미노필린|dl-메틸에페드린염산염|클로르페니라민말레산염',
       '아크리놀수화물|베르베린염화물수화물|비스무트차질산염|스코폴리아엑스10배산',
       '메타규산알루민산마그네슘|탄산수소나트륨|디아스타제·프로테아제·셀룰라제|스코폴리아엑스|리파제|감초가루|침강탄산칼슘|트리메부틴말레산염',
       '산화마그네슘', '락토바실루스카제이변종람노수스의동결건조배양물', '브로멜라인', '시트르산칼슘수화물|농축콜레칼시페롤',
       '은행엽엑스', '우르소데옥시콜산', '감초|육계|작약|생강|이부프로펜', '탄산칼슘|농축콜레칼시페롤',
       '구아야콜|황백엑스산|황련가루|감초가루|진피건조엑스', '에르도스테인',
       '메틸메티오닌설포늄염화물|스코폴리아엑스3배산|당약가루|비오디아스타제2000|리파제AP12|자소엽건조엑스|탄산마그네슘|탄산수소나트륨|침강탄산칼슘',
       '아세트아미노펜|구아이페네신|수도에페드린염산염|클로페라스틴염산염|클로르페니라민말레산염|티아민질산염|리보플라빈|감초건조엑스|길경50%에탄올건조엑스|계피건조엑스',
       '소청룡탕연조엑스|아세트아미노펜|클로르페니라민말레산염|티페피딘히벤즈산염|카페인무수물|티아민질산염|리보플라빈|제피아스코르브산',
       '메클리진염산염수화물|스코폴라민브롬화수소산염수화물|카페인무수물',
       '판크레아틴 장용과립|육계 가루|회향 가루|용담 가루|정향 가루|우르소데옥시콜산',
       '건조수산화알루미늄 겔|침강탄산칼슘|탄산마그네슘|탄산수소나트륨', '카페인무수물',
       '푸르설티아민|리보플라빈부티레이트|피리독살포스페이트수화물|히드록소코발라민아세트산염|아스코르브산|토코페롤아세테이트 2배산',
       '디멘히드리네이트', '브로멜라인|결정트립신', '수산화마그네슘', '나프록센',
       '수도에페드린염산염|클로르페니라민말레산염', '로페라미드염산염', '염화세칠피리디늄', '규산알루민산마그네슘',
       '쎄니틴 T60|쎄니틴 GBX', '아세트아미노펜|카페인무수물|이소프로필안티피린', '지실|작약|길경|건강|대추|감초',
       '카르보시스테인', '배농산급탕건조엑스', '이부프로펜', '판크레아틴|시메티콘 산|시메티콘',
       '아르니카틴크D2|카렌두라틴크 D2|하마메리스틴크D2|밀레포리움틴크D3|벨라돈나틴크D4|아코니툼틴크D3|카모밀라틴크D3|심피툼틴크D8|벨리스페렌니스틴크D2|에키나세아안구스티폴틴크D2|에키나세아플푸르틴크D2|히페리쿰틴크D2|헤파설프리스D3',
       '니푸록사지드', '건조수산화알루미늄겔|침강탄산칼슘|탄산마그네슘|탄산수소나트륨', '레보노르게스트렐|에티닐에스트라디올',
       '비오틴', '승마|목단피|당귀|황련|생지황', '파모티딘', '벤포티아민|피리독신염산염',
       '메퀴타진|벨라돈나총알칼로이드|글리시리진산이칼륨|슈도에페드린염산염|카페인무수물',
       '옥세타자인|탄산마그네슘|건조수산화알루미늄겔', '시메티딘|규산알루민산마그네슘|히드로탈시트|탄산수소나트륨',
       '아세트아미노펜|벤포티아민|리보플라빈|제피아스코르브산', '덱시부프로펜 디.씨.',
       '건조수산화알루미늄겔|탄산수소나트륨|침강탄산칼슘|탄산마그네슘|스코폴리아엑스10배산', '클로르페니라민말레산염',
       '티아민염산염|리보플라빈|피리독신염산염|니코틴산아미드|판토텐산칼슘|시아노코발라민100배산|아스코르브산과립97%',
       '피프린히드리네이트', '비오디아스타제500|리파제AP6|셀룰라제AP3', '우르소데옥시콜산|티아민질산염|리보플라빈',
       '트리프롤리딘염산염수화물|슈도에페드린염산염', '글루타티온', '아데노신트리포스페이트이나트륨삼수화물',
       '크레오소트|황련가루|감초가루|진피|향부자가루',
       '시프로헵타딘오로트산염수화물|DL-카르니틴염산염|L-리신염산염|시아노코발라민', '브롬헥신염산염',
       '방풍통성산연조엑스', '비사코딜', '옥수수불검화정량추출물', '트리프롤리딘염산염수화물|수도에페드린염산염',
       '백출|황기|방기|감초|대추|생강|이상 수침연조엑스', '유비데카레논', '메코발라민', '정제부자',
       '클레마스틴푸마르산염', '디싸이클로민염산염', '토코페롤아세테이트', 'L-카르보시스테인', '디오스민',
       '시말드레이트', '벤포티아민|피리독신염산염|시아노코발라민',
       '토코페롤아세테이트 2배산|아스코르브산|티아민질산염|리보플라빈|니코틴산아미드|판토텐산칼슘|피리독신염산염|폴산|시아노코발라민1000배산|황산아연',
       '바실루스서브티리스균·엔테로코쿠스페슘균배양물', '독시라민석시네이트', '판크레아틴|시메치콘', '염산로페라미드',
       'L-카르니틴', '비타민이프리퍼레이션',
       '시프로헵타딘오로트산염수화물|L-리신염산염|DL-카르니틴염산염|시아노코발라민',
       '바실루스서브틸리스균·엔테로코쿠스페슘균배양물', 'L-시스틴', '소브레롤', '아세틸시스테인',
       '디히드록시디부틸에테르', '독시라민숙신산염', '디시클로민염산염|파파베린염산염',
       '셀레늄함유건조효모|토코페롤아세테이트|레티놀팔미테이트유|아스코르브산',
       '푸르설티아민|리보플라빈|피리독신염산염|0.1%시아노코발라민|아스코르브산97%과립|토코페롤아세테이트50%과립',
       '알파칼시돌', '아스코르브산|비타민E', '우리딘|시티딘|글루타민', 'L-시스틴|콜린타르타르산염',
       '호박산독실아민', '판크레아틴|셀룰라제|우담즙건조엑스|디메티콘', '판크레아틴|우담즙건조엑스|디메티콘|셀룰라제',
       '철단백추출물|시아노코발라민|폴산',
       '아세트아미노펜|클로르페니라민말레산염|노스카핀|dl-메틸에페드린염산염|카페인무수물|우황|원지가루|육계가루',
       '침강탄산칼슘', '아세트아미노펜|클로르페니라민말레산염|카페인무수물',
       '빌베리건조엑스|L-시트룰린|N-아세틸-L-아스파르트산|레티놀아세테이트|토코페롤아세테이트|피리독신염산염',
       '락트산칼슘수화물|글루콘산칼슘수화물|침강탄산칼슘|에르고칼시페롤과립', '폴산',
       '판크레아틴|헤미셀룰라제|우담즙엑스|디메티콘', '아세트아미노펜제피세립',
       '우르소데옥시콜산|디아스타제·프로테아제·셀룰라제2000I|리파제II', '황련|황백|황금|치자',
       '메클리진염산염수화물',
       '디아스타제·프로테아제·셀룰라제|리파제|판프로신|판셀라제|판크레아틴장용과립|우르소데옥시콜산|시메티콘', '플루벤다졸',
       '비오디아스타제1000|리파제AP6|뉴라제', '결정글루코사민황산염',
       '락트산칼슘수화물|글루콘산칼슘수화물|침강탄산칼슘|건조에르고칼시페롤', '엘-카르니틴',
       '아스코르브산과립97%|티아민질산염|피리독신염산염|리보플라빈|판토텐산칼슘|니코틴산아미드|토코페롤아세테이트 2배산|폴산|시아노코발라민100배산|d-비오틴1%|푸마르산철',
       '티아민질산염|리보플라빈|피리독신염산염|시아노코발라민|폴산|아스코르브산|토코페롤아세테이트 2배산|d-비오틴|니코틴산아미드|판토텐산칼슘|푸마르산철',
       '피리독신염산염',
       '로얄젤리|토코페롤아세테이트|아스코르브산|티아민염산염|리보플라빈|피리독신염산염|시아노코발라민|니코틴산아미드',
       '리소짐염산염|아스코르브산|토코페롤아세테이트 2배산|카르바조크롬',
       '메타규산알루민산마그네슘|탄산수소나트륨|침강탄산칼슘|디아스타제·프로테아제·셀룰라제|리파제AP6|감초가루|스코폴리아엑스|트리메부틴말레산염',
       '탄산칼슘',
       '피리독신염산염|티아민질산염|시아노코발라민|아스코르브산|폴산|비오틴|니코틴산아미드|판토텐산칼슘|리보플라빈',
       '오르소시폰가루|다엽가루',
       '콘드로이틴설페이트나트륨|푸르설티아민|니코틴산아미드|피리독신염산염|이노시톨|판토텐산칼슘|리보플라빈부티레이트|감마오리자놀|시아노코발라민',
       '게스토덴|에치닐에스트라디올',
       '피리독신염산염|티아민질산염|시아노코발라민1000배산|리보플라빈|아스코르브산|폴산|비오틴|니코틴산아미드|판토텐산칼슘',
       '을자탕건조엑스', '토코페롤아세테이트|산화마그네슘', '건조수산화알루미늄겔|탄산마그네슘', '다엽가루|오르소시폰가루',
       '밀크시슬건조엑스산', '피코설페이트나트륨수화물', '바실루스리케니포르미스균',
       '시호가루|작약가루|택사가루|저령가루|복령가루|창출가루|육계가루|클로르페니라민말레산염|피리독신염산염|리보플라빈|티아민질산염|니코틴산아미드|판토텐산칼슘',
       '아보카도-소야불검화물의추출물', '아스코르브산', '글루콘산제이철나트륨착염',
       '당귀|작약|천궁|연교|박하|방풍|마황|대황|망초|길경|황금|석고|생강|치자|형개|백출|감초|활석',
       '인삼|황금|시호|반하|대추|감초|생강|아세트아미노펜|d-클로르페니라민말레산염|티페피딘히벤즈산염|카페인무수물|아스코르브산97%과립',
       '타우린|인삼건조엑스|우르소데옥시콜산|티아민질산염|이노시톨',
       '덱스트로메토르판브롬화수소산염수화물|구아야콜설폰산칼륨|노스카핀|dl-메틸에페드린염산염|카르비녹사민말레산염',
       '세인트존스워트80%메탄올엑스|서양승마추출액', '폴리사카리드철착염',
       '소청룡탕엑스분말|아세트아미노펜|클로르페니라민말레산염|티페피딘히벤즈산염|카페인무수물',
       '덱스트로메토르판브롬화수소산염수화물|dl-메틸에페드린염산염|노스카핀|구아야콜설폰산칼륨|말레인산카르비녹사민|감초가루|길경가루',
       '밀크시슬엑스',
       '노스카핀|dl-메틸에페드린염산염|말레인산카르비녹사민|구아야콜설폰산칼륨|덱스트로메토르판브롬화수소산염수화물',
       '메코발라민|토코페롤아세테이트 2배산|푸르설티아민염산염|피리독신염산염',
       '클로르페니라민말레산염|dl-메틸에페드린염산염|덱스트로메토르판브롬화수소산염수화물', '판테틴|콩기름불검화물|비타민E',
       '덱스트로메토르판브롬화수소산염수화물|노스카핀염산염수화물|트리메토퀴놀염산염수화물|구아이페네신|d-클로르페니라민말레산염',
       '길경|감초|작약|대추|지실|생강|석고|신이|황금|창출|치자|시호|승마|지모|맥문동|비파엽|이상수침건조엑스',
       '지실|작약|길경|건강|대추|감초|배농산급탕건조엑스', '작약|감초', '인삼40%에탄올건조엑스|은행엽건조엑스',
       '핀넨|캄펜|보르네올|아네톨|시네올|펜콘', '레보노르게스트렐|에치닐에스트라디올',
       '핀넨|캄펜|시네올|멘톤|멘톨|보르네올', '서양승마추출액|세인트존스워트80%메탄올엑스', '철-아세틸트랜스페린',
       '아스코르브산과립',
       '비타민A|건조에르고칼시페롤과립|토코페롤아세테이트|푸르설티아민|리보플라빈|피리독신염산염|시아노코발라민|아스코르브산|니코틴아마이드|폴산|판토텐산칼슘|감마-오리자놀|비오틴',
       '시호|길경|천궁|복령|연교|앵피|방풍|독활|감초|형개|생강',
       '작약가루|감초가루|아세트아미노펜|에텐자미드|카페인수화물',
       '덱스트로메토르판브롬화수소산염수화물|dl-메틸에페드린염산염|클로르페니라민말레산염|염화암모늄',
       '노스카핀|dl-메틸에페드린염산염|카르비녹사민말레산염|구아야콜설폰산칼륨|덱스트로메토르판브롬화수소산염수화물',
       '아스코르브산|리소짐염산염|토코페롤아세테이트 2배산|카르바조크롬', '클로르페니라민말레산염|페닐레프린염산염',
       '세인트존스워트80%메탄올 건조엑스|서양승마추출액', '비사코딜|틴나밸리센나열매', '방풍통성산건조엑스',
       '금은화|연교|박하|길경|감초|담죽엽|형개|두시|우방자|영양각', '메틸-N|S-디아세틸시스테인',
       '슈도에페드린염산염|트리프롤리딘염산염', '염산트리프롤리딘|염산슈도에페드린',
       '반하|황금|건강|인삼|감초|대추|황련|반하사심탕건조엑스',
       '푸르설티아민|리보플라빈|피리독신염산염|시아노코발라민|아스코르브산|토코페롤아세테이트', '배농산급탕연조엑스',
       '카페인수화물|에텐자미드|아세트아미노펜|감초가루|작약가루', '은교산건조엑스', '신이청폐탕배농산급탕가시호창출건조엑스',
       '판크레아틴|우담즙 건조엑스|디메티콘|셀룰라제',
       '시호|작약가루|저령가루|택사가루|복령가루|창출가루|육계가루|클로르페니라민말레산염|피리독신염산염|리보플라빈|티아민질산염|니코틴산아미드|판토텐산칼슘',
       '리소짐염산염|제피아스코르브산|토코페롤아세테이트 2배산|카르바조크롬',
       '아세트아미노펜|에텐자미드|구아이페네신|클로르페니라민말레산염|덱스트로메토르판브롬화수소산염수화물|황련엑스산|길경50%에탄올건조엑스',
       '덱시부프로펜디ㆍ씨', '폴리사카리드철착염|시아노코발라민1000배산|폴산',
       '아세트아미노펜|클로르페니라민말레산염|덱스트로메토르판브롬화수소산염수화물|카페인무수물|슈도에페드린염산염|구아이페네신|아스코르브산|갈근탕건조엑스[10→1]',
       '아세트아미노펜|슈도에페드린염산염|클로르페니라민말레산염',
       '베르베린탄닌산염|비스무트차질산염|스코폴리아엑스10배산|우르소데옥시콜산',
       '토코페롤아세테이트|산화마그네슘|티아민질산염|리보플라빈|피리독신염산염|니코틴산아미드', '그린티80%에탄올엑스',
       '산조인|맥문동|오미자|단삼|생지황|현삼|천문동|백자인|황련|원지|복령|인삼|당귀|길경',
       '황련|황금|황백|치자|이상수침건조엑스',
       '티아민질산염|황기 건조엑스|음양곽35%에탄올엑스|피리독신염산염|아스코르브산|판토텐산칼슘|리보플라빈|니코틴산아미드',
       '갈근탕연조엑스',
       '아스코르브산과립|니코틴산아미드|푸르설티아민|시아노코발라민1000배산|토코페롤아세테이트 2배산|리보플라빈|피리독신염산염|폴산|산화마그네슘|폴리사카리드철착염|셀레늄함유건조효모|산화아연',
       '방풍통성산건조엑스에프', '홍화유|피리독신염산염|토코페롤아세테이트',
       '리소짐염산염|카르바조크롬|아스코르브산|토코페롤아세테이트 2배산', '달맞이꽃종자유',
       '길경|감초|대추|작약|건강|지실',
       '구아이페네신|노스카핀염산염수화물|덱스트로메토르판브롬화수소산염수화물|트리메토퀴놀염산염수화물|d-클로르페니라민말레산염',
       '클로르페니라민말레산염|dl-메틸에페드린염산염|인진호탕건조엑스',
       '로얄젤리|토코페롤아세테이트 2배산|제피아스코르브산|티아민질산염|리보플라빈|니코틴산아미드|피리독신염산염|시아노코발라민',
       '수도에페드린염산염|트리프롤리딘염산염수화물', '판크레아틴|디메티콘|우담즙엑스|셀룰라제',
       '토코페롤아세테이트 2배산|히드록소코발라민아세트산염|리보플라빈부티레이트|피리독살포스페이트수화물|푸르설티아민|직타용아스코르브산',
       '도큐세이트나트륨|비사코딜', '아세트아미노펜 과립',
       '디아스타제·프로테아제·셀룰라제|dl-카르니틴염산염|우담즙건조엑스|글리시리진산암모늄|티아민염산염',
       '건조수산화알루미늄 겔', '티아민염산염', '디메티콘|판크레아틴|브로멜라인',
       '아스코르브산과립97%|리보플라빈부티레이트|피리독신염산염|토코페롤아세테이트 2배산',
       '판크레아틴|우르소데옥시콜산|시메티콘',
       '푸르설티아민|리보플라빈부티레이트|피리독살포스페이트수화물|히드록소코발라민아세트산염|아스코르브산|50%토코페롤아세테이트',
       '반하사심탕연조엑스', '바실루스서브틸리스균ㆍ스트렙토코카스페시움균배양물',
       '글리시리진산이칼륨|클로르페니라민말레산염|리보플라빈부티레이트|피리독신염산염|제피아스코르브산|판토텐산칼슘',
       '아이비엽30%에탄올엑스',
       '디아스타제·프로테아제N1|락토바실루스스포로게네스균|d-비오틴|판크레아틴장용과립|시메티콘산',
       '아세트아미노펜|수도에페드린염산염|트리프롤리딘염산염수화물', '메칠-N|S-디아세틸시스테인', '판크레아틴|시메티콘',
       '밀크시슬엑스|티아민염산염|리보플라빈|피리독신염산염|니코틴산아미드|판토텐산칼슘|시아노코발라민',
       '홍화유|토코페롤아세테이트|피리독신염산염', '티아민질산염|니코틴아마이드|아스코르빈산97%과립|피토나디온5%건조분말',
       '클로르페니라민말레산염|dl-메틸에페드린염산염|구아이페네신|덱스트로메토르판브롬화수소산염수화물',
       '글루콘산제일철수화물|니코틴산아미드|피리독신염산염|시아노코발라민1000배산|폴산|오로트산수화물|아스코르브산',
       '덱스트로메토르판브롬화수소산염수화물|노스카핀염산염수화물|트리메토퀴놀염산염수화물|구아이페네신|클로르페니라민말레산염',
       '아이비엽30%에탄올건조엑스', '센나엽|대황엑스|황|회향유|약용탄|박하유', '구연산칼슘|콜레칼시페롤',
       '육계가루|건강가루|용담가루|스코폴리아엑스|탄산수소나트륨|우르소데옥시콜산|규산알루민산마그네슘', '밀크시슬열매건조엑스',
       '레티놀팔미테이트과립|푸르설티아민|피리독신염산염3배산|시아노코발라민1000배산|토코페롤아세테이트 2배산|아스코르브산|리보플라빈부티레이트|β-카로틴20%과립|셀레늄함유건조효모|황산망간수화물|산화제이구리|산화아연',
       '아세트아미노펜|클로르페니라민말레산염|슈도에페드린염산염|카페인무수물|아스코르브산과립97%',
       '토코페롤아세테이트|아스코르브산|β-카로틴현탁액30%|유비데카레논|산화아연|셀레늄가루 0.1%',
       'β-카로틴현탁액30%|셀레늄함유건조효모|토코페롤아세테이트|아스코르브산|리보플라빈|피리독신염산염|시아노코발라민1000배산|니코틴산아미드|티아민질산염',
       '비티스비니페라엽건조엑스', '아스코르브산|리소짐염산염|카르바조크롬|토코페롤아세테이트50%',
       '방풍통성산 건조엑스에프', '시메티딘|규산알루민산마그네슘|히드로탈시드|탄산수소나트륨',
       '토코페롤아세테이트|아스코르브산|β-카로틴현탁액30%|유비데카레논|티아민질산염|리보플라빈|피리독신염산염|산화아연|셀레늄가루 0.1%',
       '아세트아미노펜|클로르페니라민말레산염|수도에페드린염산염|클로페라스틴염산염|dl-메틸에페드린염산염|구아이페네신',
       '수산화마그네슘|우르소데옥시콜산|노회엑스', '아세트아미노펜|DL-메티오닌',
       '메타규산알루민산마그네슘|탄산수소나트륨|비오디아스타제2000IV|스코폴리아엑스|리파제II|감초가루|침강탄산칼슘|트리메부틴말레산염',
       '티아민질산염|리보플라빈|피리독신염산염|시아노코발라민|니코틴산아미드|판토텐산칼슘|아스코르브산|토코페롤아세테이트 2배산|폴산',
       '방기황기탕건조엑스', '리소짐염산염|카르바조크롬|아스코르브산과립|토코페롤아세테이트 2배산',
       '시트르산칼슘수화물|콜레칼시페롤과립',
       '덱스트로메토르판브롬화수소산염수화물|dl-메틸에페드린염산염|노스카핀|구아야콜설폰산칼륨|카르비녹사민말레산염|감초가루|길경가루',
       '판크레아틴장용성제피정', '탄산칼슘|농축콜레칼시페롤분말',
       '제피아스코르브산|리소짐염산염|카르바조크롬|토코페롤아세테이트 2배산',
       '아세트아미노펜|에텐자미드|카페인무수물|클로르페니라민말레산염|덱스트로메토르판브롬화수소산염수화물|푸르설티아민염산염|리보플라빈|dl-메틸에페드린염산염',
       '아스코르브산97%과립|토코페롤아세테이트 2배산|폴산|피리독신염산염|판토텐산칼슘|리보플라빈|티아민질산염|니코틴산아미드|시아노코발라민|산화아연|비오틴|셀레늄함유건조효모',
       '글루콘산제이철나트륨착염|시아노코발라민|폴산|피리독신염산염',
       '콜린타르타르산염|DL-메티오닌|니코틴산아미드3배산|티아민질산염3배산|리보플라빈3배산|피리독신염산염3배산|판토텐산칼슘|토코페롤아세테이트 2배산|아스코르브산97%',
       '메타규산알루민산마그네슘|탄산수소나트륨|침강탄산칼슘|디아스타제·프로테아제·셀룰라제|리파제|감초가루|스코폴리아엑스|트리메부틴말레산염',
       '판크레아틴|셀룰라제|우르소데옥시콜산|시메티콘',
       '리보플라빈부티레이트|피리독신염산염|니코틴산아미드|비오틴|L-시스테인', '세인트존스워트80%메탄올건조엑스',
       '판크레아틴|디아스타제·프로테아제·셀룰라제|프로자임6|리파제|셀룰라제|우르소데옥시콜산|시메티콘', '포도엽건조엑스',
       '판크레아틴|셀룰라제|우담즙 건조엑스|디메티콘', '푸마르산철|아스코르브산|폴산|시아노코발라민1000배산',
       '옥수수불검화정량추출물|후박75%에탄올연조엑스', '사유|레티놀팔미테이트유|에르고칼시페롤|동클로로필',
       '사유|레티놀팔미테이트유|에르고칼시페롤과립|동클로로필린',
       '건조레티놀아세테이트분말|에르고칼시페롤과립|토코페롤아세테이트 2배산|아스코르브산 90%과립|티아민질산염3배산|리보플라빈3배산|피리독신염산염3배산|니코틴산아미드|시아노코발라민1000배산|유비데카레논|푸마르산철|산화마그네슘|황산망간수화물|산화아연|무수황산제이구리',
       '콘드로이틴설페이트나트륨|푸르설티아민|토코페롤아세테이트|니코틴산아미드|피리독신염산염|판토텐산칼슘|리보플라빈부티레이트|γ-오리자놀|시아노코발라민1000배산',
       '사유|레티놀팔미테이트|에르고칼시페롤|동클로로필', '포도엽엑스',
       '레티놀팔미테이트유|사유|동클로로필|에르고칼시페롤과립', '세레노아레펜스리피도스테롤추출물',
       '레티놀팔미테이트유|에르고칼시페롤|사유|동클로로필', '사유|팔미틴산레티놀유|에르고칼시페롤|동클로로필',
       '콘드로이틴설페이트나트륨|레티놀팔미테이트|에르고칼시페롤과립|리보플라빈|티아민질산염', '황산제일철 장용성 제피정',
       '비사코딜|도큐세이트나트륨|작약엑스산|우르소데옥시콜산|피리독신염산염|판토텐산칼슘', '엘카르니틴',
       '판크레아틴|우담즙엑스|디메티콘|셀룰라제', '게스토덴|에티닐에스트라디올',
       '푸르설티아민염산염|피리독살포스페이트수화물|히드록소코발라민아세트산염|리보플라빈', '구연산칼슘|콜레칼시페롤과립',
       '승마40%이소프로판올건조엑스',
       '리보플라빈부티레이트|피리독신염산염97%과립|아스코르브산97%과립|니코틴산아미드|비오틴1%|L-시스테인|의이인엑스',
       '니코틴산아미드|피리독신염산염97%과립|리보플라빈|티아민질산염|판토텐산칼슘|폴산|d-비오틴1%|시아노코발라민100배산|우르소데옥시콜산',
       '약용효모|케라틴|티아민질산염|판토텐산칼슘|L-시스틴|p-아미노벤조산',
       '길경|감초|대추|작약|건강|지실|이상물건조엑스',
       '베르베린탄닌산염|비스무트차질산염|우르소데옥시콜산|스코폴리아엑스 10배산', '아스코르브산|시트르산아연삼수화물',
       '아스코르브산97%과립|유비데카레논|피리독신염산염|시아노코발라민|폴산|티아민질산염|리보플라빈|산화아연|산화마그네슘|크롬함유건조효모|셀레늄 함유 건조효모',
       '토코페롤아세테이트|아스코르브산|β-카로틴현탁액30%|유비데카레논|산화아연|셀레늄가루 0.1%|우르소데옥시콜산',
       '콘드로이틴설페이트나트륨|푸르설티아민|리보플라빈부티레이트|니코틴산아미드|판토텐산칼슘|피리독신염산염|시아노코발라민|토코페롤아세테이트|γ-오리자놀',
       '디펜히드라민염산염', '푸마르산철|아스코르브산|폴산|시아노코발라민',
       'L-류신|L-메티오닌|L-발린|L-이소류신|L-트레오닌|L-페닐알라닌|L-트리프토판|L-리신염산염|L-아르기닌염산염|티아민질산염|토코페롤숙시네이트칼슘|리보플라빈|니코틴산아미드|피리독신염산염',
       '아세트아미노펜|클로르페니라민말레산염|클로페라스틴염산염|dl-메틸에페드린염산염|카페인무수물|세라티오펩티다제|티아민질산염|리보플라빈',
       '알긴산|카르복시메틸셀룰로오스나트륨', '비스벤티아민|피리독신염산염|시아노코발라민|토코페롤숙시네이트칼슘|니코틴산아미드',
       '센나및센나열매메탄올건조엑스|비사코딜', '비티스비니페라엽 건조엑스',
       '로얄젤리|토코페롤아세테이트|아스코르브산|티아민염산염|리보플라빈|니코틴산아미드|피리독신염산염|시아노코발라민',
       '길경|감초|작약|대추|지실|생강|석고|신이|황금|창출|치자|시호|승마|지모|맥문동|비파엽', '부틸스코폴라민브롬화물',
       '건조수산화알루미늄 겔|탄산마그네슘', '방풍통성산 건조엑스',
       '클로르페니라민말레산염|페닐레프린염산염|벨라돈나총알칼로이드',
       '초산토코페롤50%|제피아스코르빈산|카르바조크롬|염화리소짐',
       '밀크시슬열매건조엑스|티아민질산염|피리독신염산염|니코틴산아미드|판토텐산칼슘|시아노코발라민',
       'L-류신|L-메티오닌|L-발린|L-이소류신|L-트레오닌|L-페닐알라닌|L-트리프토판|L-리신염산염|L-아르기닌염산염|티아민질산염|토코페롤숙시네이트칼슘|리보플라빈|피리독신염산염|니코틴산아미드',
       '레티놀팔미테이트|농축콜레칼시페롤|티아민질산염|리보플라빈|시아노코발라민|아스코르브산',
       'L-글루탐산|L-알라닌|글리신', '비사코딜|도큐세이트나트륨|우르소데옥시콜산',
       '수산화마그네슘|우르소데옥시콜산|노회건조엑스', '디아스타제·프로테아제·셀룰라제|리파제|우르소데옥시콜산|시메티콘가루',
       'L-시스테인|아스코르브산97%과립|판토텐산 칼슘',
       '리소짐염산염|카르바조크롬|토코페롤아세테이트 2배산|아스코르브산97%',
       '인삼30%에탄올건조엑스|티아민질산염|이노시톨|타우린|우르소데옥시콜산',
       '토코페롤아세테이트|산화마그네슘|셀레늄함유건조효모', '시트르산마그네슘|판토텐산칼슘|피리독신염산염',
       '트라넥삼산|L-시스테인|아스코르브산|피리독신염산염|판토텐산칼슘',
       '길경|백출|감초|황금|석고|대황|당귀|작약|천궁|치자|연교|박하|형개|방풍|마황|생강|활석|망초|방풍통성산건조엑스에프',
       '이부프로펜|알릴이소프로필아세틸우레아|카페인무수물|산화마그네슘', '비사코딜|도큐세이트나트륨', '하르파고피툼근추출물',
       '유비데카레논|β-카로틴 현탁액30%|아스코르브산|토코페롤아세테이트|셀레늄함유건조효모|산화아연|황산망간수화물|티아민질산염|리보플라빈',
       '판크레아틴장용성제피미세정', '콘드로이틴설페이트나트륨', '히드로탈시트|글루타민|수용성아줄렌',
       '아세트아미노펜|클로르페니라민말레산염|슈도에페드린염산염', '엔테로코쿠스페슘스트레인세르넬레68균ME',
       'd-브롬페니라민말레산염|수도에페드린황산염', '클로르족사존|에텐자미드|카페인무수물', '탄산수소나트륨',
       '데소게스트렐|에티닐에스트라디올',
       '폴산|티아민질산염|리보플라빈|니코틴산아미드|피리독신염산염|아스코르브산|비오틴|시아노코발라민1000배산|판토텐산칼슘|토코페롤아세테이트 2배산|무수인산수소칼슘|황산망간|황산아연|셀레늄함유건조효모|폴리사카리드철착염',
       '아스코르브산과립|토코페롤아세테이트 2배산|폴산|티아민질산염|리보플라빈|니코틴산아미드|피리독신염산염|시아노코발라민|판토텐산칼슘|d-비오틴|황산아연수화물',
       '유비데카레논|셀레늄함유건조효모|건조레티놀아세테이트|콜레칼시페롤과립|토코페롤아세테이트 2배산|아스코르브산과립|폴산|티아민질산염|리보플라빈|니코틴산아미드|피리독신염산염|시아노코발라민|판토텐산칼슘|요오드화칼륨|푸마르산철|산화아연|황산망간수화물|황산칼륨',
       '니코틴산아미드|리보플라빈|아스코르브산|티아민염산염|레티놀팔미테이트|토코페롤아세테이트|피리독신염산염',
       '아세트아미노펜|카페인무수물|구아이페네신|dl-메틸에페드린염산염|클로르페니라민말레산염',
       '약용효모|케라틴|티아민질산염|판토텐산칼슘|L-시스틴|파라아미노벤조산',
       '유비데카레논|레티놀아세테이트 과립|콜레칼시페롤 과립|토코페롤아세테이트 2배산|직타용아스코르브산97%|폴산|리보플라빈|니코틴산아미드|피리독신염산염|시아노코발라민|판토텐산칼슘|푸마르산철|산화아연|황산망간수화물|황산칼륨|셀레늄함유건조효모|푸르설티아민',
       '티아민질산염|리보플라빈|니코틴산아미드|판토텐산칼슘|피리독신염산염|폴산|시아노코발라민|d-비오틴|콜린타르타르산염|이노시톨|γ-오리자놀|제피아스코르브산',
       '레티놀팔미테이트과립|콜레칼시페롤과립|티아민질산염|리보플라빈포스페이트나트륨|피리독신염산염|제피아스코르브산|시아노코발라민1000배산|토코페롤아세테이트 2배산|폴산|니코틴산아미드|판토텐산칼슘|글루콘산칼슘수화물|글리세로인산마그네슘',
       '인산수소칼슘수화물|글루콘산칼슘수화물|농축콜레칼시페롤',
       'β-카로틴현탁액30%|토코페롤아세테이트|γ-오리자놀|유비데카레논|피리독신염산염|시아노코발라민1000배산|황산아연|황산망간수화물|셀레늄함유건조효모|아스코르브산',
       '아세트아미노펜|구아이페네신|수도에페드린염산염|덱스트로메토르판브롬화수소산염수화물',
       '인산수소칼슘수화물|글루콘산칼슘수화물|콜레칼시페롤농축물', '탄산칼슘 91%과립|농축콜레칼시페롤',
       '건조레티놀아세테이트분말|에르고칼시페롤과립|토코페롤아세테이트 2배산|아스코르브산 90%과립|티아민질산염3배산|리보플라빈3배산|피리독신염산염3배산|니코틴산아미드|시아노코발라민1000배산|푸마르산철|산화마그네슘|황산망간수화물|산화아연|무수황산제이구리|요오드화칼륨',
       '벤포티아민|리보플라빈|니코틴산아미드|판토텐산칼슘|피리독신염산염|시아노코발라민1000배산|콜린타르타르산염|이노시톨|비오틴|폴산|산화아연|아스코르브산과립97%|토코페롤아세테이트50%|셀레늄함유건조효모|우르소데옥시콜산',
       '산화마그네슘|토코페롤아세테이트',
       '클로르페니라민말레산염|슈도에페드린염산염|덱스트로메토르판브롬화수소산염수화물|구아이페네신|아세트아미노펜',
       '피리독신염산염|리보플라빈부티레이트|셀레늄함유건조효모|시아노코발라민1000배산|니코틴산아미드|산화아연|푸르설티아민염산염|산화마그네슘|제피아스코르브산|토코페롤아세테이트 2배산|판토텐산칼슘|콜레칼시페롤과립|폴산|d-비오틴',
       '아세트아미노펜|클로르페니라민말레산염|슈도에페드린염산염|덱스트로메토르판브롬화수소산염수화물|구아이페네신',
       '아크리놀수화물|베르베린염화물수화물|스코폴리아엑스|비스무트차질산염|우르소데옥시콜산',
       '아세트아미노펜|클로르페니라민말레산염|dl-메틸에페드린염산염|슈도에페드린염산염|덱스트로메토르판브롬화수소산염수화물|구아이페네신',
       '덱스트로메토르판브롬화수소산염수화물|황련엑스산|길경엑스산|아세트아미노펜|에텐자미드|클로르페니라민말레산염',
       '직타용아스코르브산97%|토코페롤아세테이트 2배산|폴산|티아민질산염|리보플라빈|니코틴산아미드|피리독신염산염|시아노코발라민|판토텐산칼슘|d-비오틴|황산아연수화물',
       '레티놀팔미테이트과립|콜레칼시페롤과립|티아민질산염|리보플라빈포스페이트나트륨|피리독신염산염|시아노코발라빈 1000배산|제피아스코르브산|토코페롤아세테이트 2배산|폴산|니코틴산아미드|판토텐산칼슘|글루콘산칼슘수화물|글리세로인산마그네슘|비오틴',
       '베르베린염화물수화물|비스무트차질산염|우르소데옥시콜산|스코폴리아엑스10배산',
       '레티놀팔미테이트과립|콜레칼시페롤과립|티아민질산염|리보플라빈포스페이트나트륨|피리독신염산염|시아노코발라민1000배산|제피아스코르브산|토코페롤아세테이트 2배산|폴산|니코틴산아미드|판토텐산칼슘|글루콘산칼슘수화물|글리세로인산마그네슘|비오틴|황기엑스산|감초엑스산|작약엑스산|육계엑스산',
       '락토바실루스스포로게네스균|우르소데옥시콜산', '디아스타제·프로테아제|탄산수소나트륨|메타규산알루민산마그네슘',
       '피리독신염산염|D-비오틴|시아노코발라민1000배산|토코페롤아세테이트 2배산|폴산|벤포티아민|니코틴산아미드|판토텐산칼슘|산화아연|직타용아스코르브산97%|우르소데옥시콜산|이노시톨|리보플라빈|콜린타르타르산염|셀레늄함유건조효모|γ-오리자놀|인산수소칼슘수화물|산화마그네슘',
       '푸르설티아민|니코틴산아미드|판토텐산칼슘|피리독신염산염|시아노코발라민1000배산|d-비오틴|아스코르브산97%과립',
       '벤포티아민|리보플라빈|니코틴산아미드|판토텐산칼슘|피리독신염산염|폴산|콜린타르타르산염|이노시톨|D-비오틴|산화아연|직타용아스코르브산97%|시아노코발라민1000배산|토코페롤아세테이트 2배산|우르소데옥시콜산|셀레늄함유건조효모|에르고칼시페롤과립|푸르설티아민',
       '벤포티아민|리보플라빈|니코틴산아미드|판토텐산칼슘|피리독신염산염|시아노코발라민1000배산|콜린타르타르산염|이노시톨|d-비오틴|폴산|산화아연|제피아스코르브산|셀레늄함유건조효모|콜레칼시페롤과립|산화마그네슘|무수인산수소칼슘|γ-오리자놀|DL-메티오닌',
       '센텔라정량추출물', '비사코딜|도큐세이트나트륨|센노사이드칼슘',
       '아스코르브산과립97%|티아민질산염|피리독신염산염|리보플라빈|판토텐산칼슘|니코틴산아미드|토코페롤아세테이트 2배산|폴산|시아노코발라민100배산|유비데카레논10%|푸마르산철|산화마그네슘|염화칼륨',
       '티아민염산염|니코틴산아미드|판토텐산칼슘|리보플라빈|폴산|d-비오틴|시아노코발라민1000배산|콜린타르타르산염|피리독신염산염|이노시톨|벤포티아민|유비데카레논|산화마그네슘|γ-오리자놀',
       '시아노코발라민1000배산|벤포티아민|리보플라빈|푸르설티아민|산화마그네슘|판토텐산칼슘|이노시톨|우르소데옥시콜산|산화아연|D-비오틴|직타용아스코르브산97%|피리독신염산염|폴산|셀레늄함유건조효모|토코페롤아세테이트 2배산|니코틴산아미드|γ-오리자놀',
       '탄산칼슘|농축콜레칼시페롤|무수황산제이구리|산화아연|산화마그네슘|황산망간수화물',
       '피리독신염산염|티아민질산염|시아노코발라민 1000배산|리보플라빈|아스코르브산과립|폴산|d-비오틴|니코틴산아미드|판토텐산칼슘',
       'L-카르보시스테인|브롬헥신염산염',
       '히드로탈시트|침강탄산칼슘|탄산수소나트륨|우르소데옥시콜산|육계유|회향유|디아스타제·프로테아제·셀룰라제1000|프로자임|리파제',
       '아세트아미노펜|dl-메틸에페드린염산염|덱스트로메토르판브롬화수소산염수화물|구아이페네신',
       '시아노코발라민1000배산|벤포티아민|리보플라빈|판토텐산칼슘|이노시톨|우르소데옥시콜산|산화아연|D-비오틴|직타용아스코르브산97%|피리독신염산염|폴산|셀레늄함유건조효모|토코페롤아세테이트 2배산|니코틴산아미드|유비데카레논|콜린타르타르산염|DL-메티오닌',
       '콜레칼시페롤과립', '판크레아스분말', '시트르산칼슘|농축콜레칼시페롤 과립',
       'γ-오리자놀|푸르설티아민|니코틴산아미드|콜린타르타르산염|판토텐산칼슘|리보플라빈부티레이트|이노시톨|콘드로이틴설페이트나트륨|피리독신염산염|시아노코발라민1000배산',
       '아세트아미노펜|구아이페네신|페닐레프린염산염|덱스트로메토르판브롬화수소산염수화물|dl-메틸에페드린염산염|디펜히드라민염산염',

In [87]:
data[data['di_etc_otc_code'] == '일반의약품' ]['di_class_no'].unique()

array(['[02390]기타의 소화기관용약', '[01310]안과용제', '[01410]항히스타민제',
       '[03980]종합대사성제제', '[01140]해열.진통.소염제', '[06420]구충제', '[02150]혈관보강제',
       '[03130]비타민 B제(비타민 B1을 제외)', '[02330]건위소화제',
       '[03990]따로 분류되지 않는 대사성 의약품', '[03210]칼슘제', '[02380]하제, 완장제',
       '[03160]혼합비타민제(비타민AD 혼합제제를 제외)', '[02220]진해거담제', '[01320]이비과용제',
       '[01240]진경제', '[02190]기타의 순환계용약', '[02340]제산제',
       '[03140]비타민 C 및 P제', '[02310]치과구강용약', '[02290]기타의 호흡기관용약',
       '[03110]비타민 A 및 D제', '[03190]기타의 비타민제', '[02320]소화성궤양용제',
       '[02370]정장제', '[01220]골격근이완제', '[02350]최토제, 진토제', '[03950]효소제제',
       '[03910]간장질환용제', '[01150]각성제,흥분제', '[02550]비뇨생식기관용제(성병예방제포함)',
       '[02630]화농성질환용제', '[04900]기타의 조직세포의 기능용의약품', '[02540]피임제', nan,
       '[03920]해독제', '[01190]기타의 중추신경용약', '[02110]강심제',
       '[03150]비타민 E 및 K제', '[01120]최면진정제', '[03250]단백아미노산제제',
       '[02360]이담제', '[03220]무기질제제', '[03120]비타민 B1제', '[02560]치질용제',
       '[01490]기타의 알레르기용약', '[03290]기타의 자양강장변질제', '[02180]동맥경화용제',
       '[02590]기타의 비뇨생식기관 및 항문용약', '[04290]기타의 종양치료제', '[02690]기타의 외피용약',
       '[01900]기타의 신경계및 감각기관용 의약품'], dtype=object)

In [79]:
data[data['di_etc_otc_code'] == '일반의약품' ]['color_class1'].unique()

array(['연두', '갈색', '빨강', '분홍', '하양', '주황', '초록', '파랑', '노랑', '하양, 빨강',
       nan, '주황, 투명', '청록', '보라', '회색', '노랑, 투명', '갈색, 투명', '초록, 투명',
       '하양, 갈색', '청록, 투명', '파랑, 투명', '빨강, 투명', '검정', '투명', '보라, 투명',
       '하양, 파랑', '자주', '분홍, 투명'], dtype=object)

In [ ]:
data.loc[(data['di_etc_otc_code'] == '일반의약품') & (data['di_class_no'] == '[01140]해열.진통.소염제') & (data['drug_shape'] == '장방형') & (data['color_class1'] == '하양')]['dl_name'].unique()

array(['렉스펜정 300mg/PTP', '맥시부펜이알정 300mg', '펜잘이알서방정(아세트아미노펜)',
       '푸러펜정 300mg/PTP', '크로아존정 300mg/PTP', '소니펜정 300mg', '근편정 300mg/PTP',
       '하벤코정 500mg/PTP', '타세놀정500mg/PTP', '아니스펜8시간이알서방정(아세트아미노펜)',
       '나프록소정(나프록센나트륨)', '파나덱스정 300mg', '담엔싹정 300mg/PTP', '부루펜정 400mg',
       '부루펜정 200mg', '세록센정', '세토펜정', '리오루펜정 400mg', '판피린티정 300mg/통',
       '이바펜400mg정', '삼익아세트아미노펜정 500mg', '아스타펜정 325mg', '펜세타정',
       '타스펜8시간이알서방정 650mg', '디퓨탭서방정', '하벤목캡슐 21mg/PTP', '하디코정 500mg/PTP',
       '티메롤이알서방정(아세트아미노펜)', '코애드에프정 30mg/PTP', '타이레놀정500mg',
       '타이레놀정 160mg', '셀라펜정 300mg/PTP', '타이레놀이알서방정(아세트아미노펜)(수출용)',
       '속코정 500mg/PTP', '타이펜8시간이알서방정', '하벤파워에스캡슐 200mg/PTP',
       '타이리콜8시간이알서방정', '다아펜정 450mg/PTP', '나프록스정 275mg', '코크린정 500mg/PTP',
       '오메코프에스캡슐 15mg/PTP', '신신아렉스정 300mg/PTP', '펜타우드정(덱시부프로펜)',
       '시노피드플러스정 500mg/PTP', '세토펜이알서방정500정', '모아코정 500mg/PTP',
       '지펜정 300mg', '타세놀이알서방정(아세트아미노펜)', '맥스펜정(덱시부프로펜디.씨)',
       '리렉스펜정 300mg/PTP', '엔시드8시간이알서방정 650mg', '피로펜정 300mg/PTP',
       '클라펜정 300mg/PTP', '데이감에스정 500mg/PTP', '써스펜8시간이알서방정 650mg',
       '클록펜정 300mg/PTP', '디펜코정 500mg/PTP', '아페린정 25mg/병',
       '크린탈정 500mg/PTP', '리렉사정 300mg/PTP', '히트펜정 25mg/병', '이알펜8시간서방정',
       '타미스펜8시간이알서방정'], dtype=object)

In [89]:
data.loc[(data['di_etc_otc_code'] == '일반의약품') & (data['di_class_no'] == '[01140]해열.진통.소염제') & (data['drug_shape'] == '장방형') & (data['color_class1'] == '하양')][['folder', 'file_name']]

        folder                        file_name
16    TL_10_단일  K-020330_0_0_0_0_60_000_200.png
38    TL_10_단일  K-022362_0_0_0_0_60_000_200.png
253   TL_15_단일  K-032083_0_0_0_0_60_000_200.png
265   TL_15_단일  K-032607_0_0_0_0_60_000_200.png
274   TL_15_단일  K-033059_0_0_0_0_60_000_200.png
...        ...                              ...
3985   TL_9_단일  K-017040_0_0_0_0_60_000_200.png
3999   TL_9_단일  K-017587_0_0_0_0_60_000_200.png
4159   VL_2_단일  K-040434_0_2_0_0_75_000_200.png
4324   VL_6_단일  K-042268_0_2_0_0_75_000_200.png
4349   VL_6_단일  K-042519_0_0_0_0_75_000_200.png

[63 rows x 2 columns]

# 일반의약품 진통제 하양 데이터

In [15]:
painkiller_general_white = data.loc[(data['di_etc_otc_code'] == '일반의약품') & (data['di_class_no'] == '[01140]해열.진통.소염제') & (data['color_class1'] == '하양')]

In [17]:
painkiller_general_white['folder_prefix'] = painkiller_general_white['folder'].str.split('_').str[0]
painkiller_general_white['folder_num'] = painkiller_general_white['folder'].str.split('_').str[1].astype(int)

C:\Users\user\AppData\Local\Temp\ipykernel_21012\486868864.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  painkiller_general_white['folder_prefix'] = painkiller_general_white['folder'].str.split('_').str[0]
C:\Users\user\AppData\Local\Temp\ipykernel_21012\486868864.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  painkiller_general_white['folder_num'] = painkiller_general_white['folder'].str.split('_').str[1].astype(int)

In [ ]:
painkiller_general_white.sort_values(by=['folder_prefix', 'folder_num'])['folder'].value_counts(sort=False)

folder
TL_1_단일      1
TL_3_단일      5
TL_4_단일      2
TL_5_단일      3
TL_6_단일      7
TL_7_단일     12
TL_8_단일      1
TL_9_단일      2
TL_10_단일     3
TL_13_단일     1
TL_14_단일     1
TL_15_단일     6
TL_16_단일     2
TL_18_단일     2
TL_19_단일     4
TL_21_단일     1
TL_26_단일     1
TL_27_단일     3
TL_28_단일     1
TL_29_단일     8
TL_31_단일     1
TL_33_단일     2
TL_34_단일     1
TL_35_단일     2
TL_37_단일     3
TL_38_단일     1
TL_41_단일     1
TL_43_단일     1
TL_46_단일     3
TL_57_단일     1
TL_59_단일     1
TL_61_단일     1
TL_68_단일     1
TL_69_단일     1
VL_2_단일      1
VL_6_단일      3
Name: count, dtype: int64

In [21]:
folder_names = painkiller_general_white['folder'].unique().tolist()
folder_names

['TL_10_단일',
 'TL_13_단일',
 'TL_14_단일',
 'TL_15_단일',
 'TL_16_단일',
 'TL_18_단일',
 'TL_19_단일',
 'TL_1_단일',
 'TL_21_단일',
 'TL_26_단일',
 'TL_27_단일',
 'TL_28_단일',
 'TL_29_단일',
 'TL_31_단일',
 'TL_33_단일',
 'TL_34_단일',
 'TL_35_단일',
 'TL_37_단일',
 'TL_38_단일',
 'TL_3_단일',
 'TL_41_단일',
 'TL_43_단일',
 'TL_46_단일',
 'TL_4_단일',
 'TL_57_단일',
 'TL_59_단일',
 'TL_5_단일',
 'TL_61_단일',
 'TL_68_단일',
 'TL_69_단일',
 'TL_6_단일',
 'TL_7_단일',
 'TL_8_단일',
 'TL_9_단일',
 'VL_2_단일',
 'VL_6_단일']

In [22]:
code_map = {}
for key in folder_names:
    code_map[key] = painkiller_general_white.loc[painkiller_general_white['folder'] == key, 'c-code'].tolist()

In [24]:
print(code_map)

{'TL_10_단일': ['K-019843', 'K-020330', 'K-022362'], 'TL_13_단일': ['K-028623'], 'TL_14_단일': ['K-029910'], 'TL_15_단일': ['K-032083', 'K-032243', 'K-032607', 'K-033059', 'K-033609', 'K-033746'], 'TL_16_단일': ['K-034582', 'K-036982'], 'TL_18_단일': ['K-040998', 'K-041290'], 'TL_19_단일': ['K-045103', 'K-045583', 'K-045658', 'K-046737'], 'TL_1_단일': ['K-001029'], 'TL_21_단일': ['K-000399'], 'TL_26_단일': ['K-003510'], 'TL_27_단일': ['K-004120', 'K-004315', 'K-004490'], 'TL_28_단일': ['K-005181'], 'TL_29_단일': ['K-005300', 'K-005440', 'K-005562', 'K-005570', 'K-005579', 'K-005649', 'K-005650', 'K-005666'], 'TL_31_단일': ['K-006672'], 'TL_33_단일': ['K-008859', 'K-008876'], 'TL_34_단일': ['K-010141'], 'TL_35_단일': ['K-010537', 'K-010920'], 'TL_37_단일': ['K-011976', 'K-012130', 'K-012234'], 'TL_38_단일': ['K-012968'], 'TL_3_단일': ['K-004378', 'K-004637', 'K-004799', 'K-005025', 'K-005886'], 'TL_41_단일': ['K-014619'], 'TL_43_단일': ['K-015427'], 'TL_46_단일': ['K-017343', 'K-017462', 'K-017480'], 'TL_4_단일': ['K-006977', 'K-007235'], 'TL_57_단일': ['K-025532'], 'TL_59_단일': ['K-026675'], 'TL_5_단일': ['K-008902', 'K-009552', 'K-010140'], 'TL_61_단일': ['K-027962'], 'TL_68_단일': ['K-031321'], 'TL_69_단일': ['K-031952'], 'TL_6_단일': ['K-010538', 'K-010738', 'K-010955', 'K-011166', 'K-011613', 'K-011617', 'K-011780'], 'TL_7_단일': ['K-011846', 'K-011942', 'K-011982', 'K-012081', 'K-012244', 'K-012758', 'K-012914', 'K-013326', 'K-013378', 'K-013395', 'K-013470', 'K-013474'], 'TL_8_단일': ['K-015537'], 'TL_9_단일': ['K-017040', 'K-017587'], 'VL_2_단일': ['K-040434'], 'VL_6_단일': ['K-042268', 'K-042519', 'K-042854']}

# 일반의약품 진통제 장방형 하양 데이터

In [90]:
painkiller_general_white = data.loc[(data['di_etc_otc_code'] == '일반의약품') & (data['di_class_no'] == '[01140]해열.진통.소염제') & (data['drug_shape'] == '장방형') & (data['color_class1'] == '하양')]

In [92]:
painkiller_general_white['dl_name']

16        렉스펜정 300mg/PTP
38         맥시부펜이알정 300mg
253     펜잘이알서방정(아세트아미노펜)
265       푸러펜정 300mg/PTP
274      크로아존정 300mg/PTP
              ...
3985      크린탈정 500mg/PTP
3999      리렉사정 300mg/PTP
4159         히트펜정 25mg/병
4324           이알펜8시간서방정
4349        타미스펜8시간이알서방정
Name: dl_name, Length: 63, dtype: object

In [94]:
painkiller_general_white.to_csv("C:\Potenup\Drug-Detection-Chatbot\data\drug_pankiller_genelral_white_roundsquare_data.csv", index=None)

In [3]:
painkiller_general_white = pd.read_csv("C:\Potenup\Drug-Detection-Chatbot\data\drug_pankiller_genelral_white_roundsquare_data.csv")

In [ ]:
foler_names = painkiller_general_white['folder'].unique().tolist()
foler_names = sorted(foler_names, key = lambda x: (x.split('_')[0], int(x.split('_')[1])))
foler_names

['TL_1_단일',
 'TL_3_단일',
 'TL_4_단일',
 'TL_6_단일',
 'TL_7_단일',
 'TL_8_단일',
 'TL_9_단일',
 'TL_10_단일',
 'TL_15_단일',
 'TL_16_단일',
 'TL_18_단일',
 'TL_19_단일',
 'TL_21_단일',
 'TL_26_단일',
 'TL_27_단일',
 'TL_28_단일',
 'TL_29_단일',
 'TL_33_단일',
 'TL_37_단일',
 'TL_38_단일',
 'TL_41_단일',
 'TL_43_단일',
 'TL_46_단일',
 'TL_57_단일',
 'TL_61_단일',
 'TL_68_단일',
 'VL_2_단일',
 'VL_6_단일']

In [35]:
painkiller_general_white['folder_prefix'] = painkiller_general_white['folder'].str.split('_').str[0]
painkiller_general_white['folder_num'] = painkiller_general_white['folder'].str.split('_').str[1].astype(int)

In [48]:
painkiller_general_white.sort_values(by=['folder_prefix', 'folder_num'])['folder'].value_counts(sort=False)

folder
TL_1_단일      1
TL_3_단일      4
TL_4_단일      1
TL_6_단일      5
TL_7_단일     10
TL_8_단일      1
TL_9_단일      2
TL_10_단일     2
TL_15_단일     5
TL_16_단일     2
TL_18_단일     2
TL_19_단일     2
TL_21_단일     1
TL_26_단일     1
TL_27_단일     3
TL_28_단일     1
TL_29_단일     3
TL_33_단일     2
TL_37_단일     3
TL_38_단일     1
TL_41_단일     1
TL_43_단일     1
TL_46_단일     3
TL_57_단일     1
TL_61_단일     1
TL_68_단일     1
VL_2_단일      1
VL_6_단일      2
Name: count, dtype: int64

In [ ]:
painkiller_general_white.sort_values(by=['folder_prefix', 'folder_num'])[['folder', 'c-code']]

      folder    c-code
13   TL_1_단일  K-001029
29   TL_3_단일  K-004378
30   TL_3_단일  K-004799
31   TL_3_단일  K-005025
32   TL_3_단일  K-005886
..       ...       ...
40  TL_61_단일  K-027962
41  TL_68_단일  K-031321
60   VL_2_단일  K-040434
61   VL_6_단일  K-042268
62   VL_6_단일  K-042519

[63 rows x 2 columns]

In [ ]:
painkiller_general_white.loc[painkiller_general_white['folder'] == 'TL_6_단일', 'c-code'].tolist()